### ISSUE TITLE
Allow GUID to be used in Client-id parameter

### ISSUE THREAD

**Issue by ericsleung** [xamarin/mqtt#158]
When trying to connect with GUID "7e6efa94-50d6-4d3d-85ff-74663a6ef000", the library throws the below exception:
_An error occurred while trying to connect the client "7e6efa94-50d6-4d3d-85ff-74663a6ef000"
at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__28.MoveNext() in C:\Code\Xamarin\mqtt\src\Client\Sdk\MqttClientImpl.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()_

Also, the library doesn’t return an exact cause of connection failure. It throws a generic exception in all cases. There is no indicator to identify root cause or to take alternate action based on failure reason.  Paho M2Mqtt library provides different error codes for connection failures.
The client "7e6efa94-50d6-4d3d-85ff-74663a6ef000" has been disconnected while trying to perform the connection
at System.Net.Mqtt.Sdk.MqttClientImpl.<ConnectAsync>d__28.MoveNext() in C:\Code\Xamarin\mqtt\src\Client\Sdk\MqttClientImpl.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by mauroa** [comment]
Thanks for reporting the issue. We will take a look based on the sample and get you back soon

**Comment by romannovotny** [comment]
When I used Guid as clientId there is no error, but I can't receive any message now.
