### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Rajkumar181** [xamarin/mqtt#172]
I install the packages and i got this error.

Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Reactive.Linq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'System.Reactive.Linq.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	mqttTest2

**Comment by Rajkumar181** [comment]
This is resolve. When i added This

Install-Package Rx-Main -Version 2.3.0-beta2

**Comment by Rajkumar181** [comment]
Again i am getting some other error in Subscribe.


 Client.MessageStream.Subscribe(msg =>
                    {                
                     MessageSub = System.Text.Encoding.UTF8.GetString(msg.Payload);
                        Messages.Add(new Item { Text = MessageSub.ToString() });
                    });


Error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0121	The call is ambiguous between the following methods or properties: 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>)' and 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>)'	mqtttest	C:\Users\iRam14\Documents\Visual Studio 2015\Projects\mqtttest\mqtttest\MainActivity.cs	260	Active
